### ISSUE TITLE
Word Search/Spell Check

### ISSUE THREAD

**Issue by JMichaelScott** [dbeattyspace/beatty_CSCI2270Final#2]
The isLeaf flag does not seem to switch to true properly when the program initially loads the text file. For instance, if I search for "yams" it says they are not found. If I traverse the tree and spell yams, it is present, but the 's' is not a leaf, the blank node following is showed as a leaf.
![search error](https://cloud.githubusercontent.com/assets/18425834/15025093/e0adacf4-11f4-11e6-8a34-840af4d50d0d.PNG)

If I add "yams" to the dictionary, it correctly flags the 's' as a leaf and can find it.
![search found](https://cloud.githubusercontent.com/assets/18425834/15025131/0f27ff94-11f5-11e6-9f61-39eba823d1fe.PNG)

This also seems to affect the spellcheck algorithm. I'm looking into fixed it.

**Comment by dbeattyspace** [comment]
Thanks!
It's possible that 'yams' isn't in the text file that it uses to build the
dictionary.

Thanks for pointing that out though.

**Comment by JMichaelScott** [comment]
It is in the dictionary, as far as I can tell. From a basic search, I can't seem to find any words present in the dictionary. Even though they are all loaded in.
![more search](https://cloud.githubusercontent.com/assets/18425834/15025278/b661c060-11f5-11e6-81ad-8c936efedf1d.PNG)
